import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'flowbite';
import { useEffect } from "react";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  
  title: "PixelFlows Admin",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.className}`}>
        {children}
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"
          async
        ></script>
      </body>
    </html>
  );
}
